name: Build Image CI

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u culture4web --password-stdin
      - name: Build the Docker image
        run: docker build -t ${{ github.event.inputs.image-tag }} .
      - name: Push the Docker image
        run: docker push culture4web/culture-web-fe:${{ github.event.inputs.image-tag }}
